version: '3.4'

networks:
  backend:

services:
  basedb:
    container_name: main-database
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=dY^9E3&DaC
    networks:
      - backend
    ports:
      - 1533:1433

  seq:
    container_name: seq-log-manager
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    networks:
      - backend    
    ports:
      - 5341:5341
      - 5340:80

  configurationbag.endpoint.api:
    container_name: configuration-bag
    image: ${DOCKER_REGISTRY-}configurationbagendpointapi
    build:
      context: .
      dockerfile: src/ConfigurationBag.EndPoint.Api/Dockerfile
    networks:
      - backend
    ports:
      - 800:80    
    environment:
      - DB_HOST=main-database
      - DB_NAME=ConfigurationBag
      - DB_USER=SA
      - DB_PASSWORD=dY^9E3&DaC
      - SEQ_URL=http://seq:5341
      - SEQ_API_KEY=iFmSvnjnngyWk88CRpsB



